#!/usr/bin/env sh

# Debug
yabai -m config debug_output on
# window settings
yabai -m config window_topmost on
#yabai -m config window_opacity_duration 0.0
yabai -m config window_shadow float
# window borders moved to limelight
# allow space for https://github.com/somdoron/spacebar
yabai -m config external_bar all:26:0
# opacity
yabai -m config window_opacity off
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 1.0

# general tiling settings
yabai -m config layout bsp
yabai -m config window_placement second_child
# padding and gaps
yabai -m config window_gap 2
yabai -m config top_padding 1
yabai -m config bottom_padding 1
yabai -m config left_padding 1
yabai -m config right_padding 1

# split ratio
yabai -m config split_ratio 0.50
yabai -m config auto_balance off

# mouse support
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse off
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

## Window Rules
# Desktop assignments
yabai -m rule --add app=Alacritty title!="popup-prompt" space=^1
# grid=<rows>:<cols>:<start-x>:<start-y>:<width>:<height>
yabai -m rule --add label=doom-capture title="doom-capture" manage=off grid=4:4:1:1:2:2
yabai -m rule --add app="^Spotify$" manage=on
# TODO "Microsoft Remote Desktop" # a thorn in my side
# Unmanaged Windows
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="Finder" title="Copy" manage=off
yabai -m rule --add app="App Store" manage=off
# float emacs popups
#yabai -m rule --add label="EmacsPopup" app=Emacs title!=".*Doom.*" manage=off
# TODO fix emacs popups    "title":"  —  (92 × 46)",
#yabai -m rule --add label="EmacsPopup" title='^  —  \(.*\)$'

# send Firefox and Emacs to last space when monitor changes otherwise to 5
display_count=$(yabai -m query --displays|jq length)
if [ $display_count -ge 2 ]; then
  second_space=$(yabai -m query --displays | jq 'map(select(."index" == 2))[].spaces[]')

  yabai -m rule --add label="Emacs" app=Emacs \
	  title!="doom-capture" manage=on space=$second_space
  yabai -m rule --add label="FFDisplays" app="Firefox" title!="^.{0}$" \
	  manage=on space=$second_space sticky=off
  echo "Firefox and Emacs moved to second display"
else
  yabai -m rule --add label="Emacs" app=Emacs title!="doom-capture" manage=on space=^2 
  yabai -m rule --add label="FFDisplays" app="^Firefox$" title!="^.{0}$" manage=on space=4
  echo "Firefox and Emacs moved to laptop display"
fi

# move FF based on signal when 2nd monitor connected?
# https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#signal
yabai -m signal --add event=display_added \
	action='yabai -m rule --add label="FFDisplays" app="Firefox" title!="^.{0}$" manage=on space=$(yabai -m query --spaces|jq length) sticky=off'
yabai -m signal --add event=display_removed \
	action='yabai -m rule --add label="FFDisplays" app="Firefox" title!="^.{0}$" manage=on space=4 sticky=off'
# TODO If attached to XPS: system_profiler SPDisplaysDataType|grep 'XPS 2720'
# then send emacs to last workspace in addition to Firefox, ensure vertical tiling and focus alacritty space 1

# Manage Teams on to tile but not notifications, until they are no longer "subrole":"AXStandardWindow"
#yabai -m rule --add app="Microsoft Teams" manage=on title!='^Microsoft Teams Notification$' space=3 # layer=below
#yabai -m rule --add app="Microsoft Teams" manage=off title='^Microsoft Teams Notification$' space=3
# Ignore Teams tool tips have zero length title
#yabai -m rule --add app="Microsoft Teams" manage=off title!='^.{0}$' space=3

# Microsoft Teams Notification
# https://github.com/koekeishiya/yabai/issues/74
# Disable border and float window
yabai -m rule --add label=ignoreTeamsNotification \
  app='^Microsoft Teams$' \
  title='^Microsoft Teams Notification$' \
  manage=off \
  border=off

# Tries to focus the main Teams window whenever the notification gains focus, because it always takes focus first.
yabai -m signal --add \
  event=window_focused \
  app='^Microsoft Teams$' \
  title='^Microsoft Teams Notification$' \
  action="yabai -m window --focus $(yabai -m query --windows --space 3 | jq '.[] |select(.title | contains("| Microsoft Teams"))? | .id')"

# TODO add rule for FF pop out to do this, but slightly larger?
# toggle sticky, float and resize to picture-in-picture size
# shift + alt - p : yabai -m window --toggle sticky;\
#                   yabai -m window --grid 5:5:4:0:1:1
# grid=<rows>:<cols>:<start-x>:<start-y>:<width>:<height>
#yabai -m rule --add label=ffPIP app="Firefox" title="Picture-in-Picture" layer=above sticky=on manage=off grid=5:5:4:0:1:1
# yabai -m signal --add lable=ffPIP \
#   event=window_created \
#   app="Firefox" title="Picture-in-Picture" \
#   action='yabai -m window --toggle sticky; yabai -m window --grid=5:5:4:0:1:1'

# # yabai -m query --spaces --display| jq 'map(select(."focused" == 1))'

echo "yabai configuration loaded.."
