#!/usr/bin/env sh

# bar settings
yabai -m config status_bar                   on
yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
#yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X
#greek: alpha, beta, gamma, delta, epsilon, zeta, eta, theta, iota
yabai -m config status_bar_space_icon_strip  α β γ δ ε ζ η θ ι
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config window_border                off
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  1
yabai -m config bottom_padding               1
yabai -m config left_padding                 1
yabai -m config right_padding                1
yabai -m config window_gap                   2

## Window Rules
# Desktop assignments
yabai -m rule --add app=Alacritty space=^1
yabai -m rule --add app=Emacs manage=on space=2 floating=off
# Manage off until notifications are no longer "subrole":"AXStandardWindow"
yabai -m rule --add app="Microsoft Teams" manage=off space=3 
yabai -m rule --add app="Xcode" manage=on space=4
yabai -m rule --add app="^Spotify$" manage=on space=4
# TODO "Microsoft Remote Desktop" # a thorn in my side
# Unmanaged Windows
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="Finder" title="Copy" manage=off
yabai -m rule --add app="App Store" manage=off

# TODO move FF based on signal when 2nd monitor connected?
# https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#signal
# # if dual screen, send Firefox to 5 else to 4
if [ "$(yabai -m query --displays |jq '.|length')" -eq 2 ];then
    yabai -m rule --add label="FFDisplays" app="Firefox" manage=on space=5
    echo "2 displays, assigning Firefox to desktop 5"
else
    yabai -m rule --add label="FFDisplays" app="Firefox" manage=on space=4
    echo "Single display, assigning Firefox to desktop 4"
fi

# Microsoft Teams Notification
# https://github.com/koekeishiya/yabai/issues/74
# Disable border and float window
yabai -m rule --add \
    label=ignoreTeamsNotification \
    app='^Microsoft Teams$' \
    title='^Microsoft Teams Notification$' \
    manage=off \
    border=off

# Tries to focus the window under the cursor whenever the MS teams notification gains focus
# Probably conflicts with mouse follows focus in some ways
yabai -m signal --add \
    event=window_focused \
    app='^Microsoft Teams$' \
    title='^Microsoft Teams Notification$' \
    action='yabai -m window --focus mouse > /dev/null 2>&1'

# TODO 
# yabai -m signal --add \
#     event=display_added \
#     app='^Firefox$' \
#     action='yabi -m rule --add app="Firefox" manage=on space=5'

# yabai -m signal --add \
#     event=display_removed \
#     app='^Firefox$' \
#     action='yabi -m rule --add app="Firefox" manage=on space=4'

echo "yabai configuration loaded.."
 
